# Copyright (C) 2020 Alexandros Theodotou <alex at zrythm dot org>

language: c
os:
  - osx

before_install:
- |-
  set -e
  brew update
  # use || true because it returns 1
  brew install fftw meson libsamplerate sdl2 chromaprint libgtop lilv librsvg adwaita-icon-theme gtk+3 guile gtksourceview4 graphviz zstd npm || true
  brew link --overwrite python
  npm install -g appdmg
  pwd
  git clone https://git.sr.ht/~alextee/mxe
  git clone https://git.sr.ht/~alextee/zrythm
  git clone https://git.sr.ht/~alextee/zrythm-builds
  git clone https://git.sr.ht/~alextee/zrythm-installer
  git clone https://github.com/KDE/breeze-icons
  git clone https://github.com/mesonbuild/meson
  echo "$SSH_PRIVATE_KEY" > tmp_rsa
  openssl base64 -d -A < tmp_rsa > id_rsa
  grep -q "BEGIN RSA PRIVATE KEY" id_rsa

script:
- |-
  set -e
  zrythm-builds/scripts/make-pkg.sh osx
