# Copyright (C) 2020 Alexandros Theodotou <alex at zrythm dot org>

language: c
os: osx
osx_image: xcode11.5

script:
  - |-
    set -e
    git clone https://git.sr.ht/~alextee/mxe
    git clone https://git.sr.ht/~alextee/zrythm
    git clone https://git.sr.ht/~alextee/zrythm-builds
    git clone https://git.sr.ht/~alextee/zrythm-installer
    git clone https://github.com/KDE/breeze-icons
    git clone https://github.com/mesonbuild/meson
    echo "$SSH_PRIVATE_KEY" > tmp_rsa
    openssl base64 -d -A < tmp_rsa > id_rsa
    grep -q "BEGIN RSA PRIVATE KEY" id_rsa
    chmod 600 id_rsa
    zrythm-builds/scripts/create-manuals-zip.sh osx-brew-zip
    zrythm-builds/scripts/make-pkg.sh osx-brew-zip
    zrythm-builds/scripts/push-pkg.sh osx-brew-zip

addons:
  homebrew:
    packages:
      - fftw
      - meson
      - libsamplerate
      - sdl2
      - chromaprint
      - lilv
      - librsvg
      - adwaita-icon-theme
      - gtk+3
      - guile
      - gtksourceview4
      - graphviz
      - zstd
      - rt-audio
      - rtmidi
    update: true
