#
# Copyright (C) 2020 Alexandros Theodotou <alex at zrythm dot org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

trigger:
- master
- nightlies

pool:
  vmImage: 'macOS-latest'

steps:
- script: |
    set -e
    brew update
    # use || true because it returns 1
    brew install fftw meson libsamplerate sdl2 chromaprint libgtop lilv librsvg adwaita-icon-theme gtk+3 guile gtksourceview4 graphviz zstd npm rt-audio rtmidi carla || true
    brew link --overwrite python
    #npm install -g appdmg
    pwd
    git clone https://git.sr.ht/~alextee/mxe
    git clone https://git.sr.ht/~alextee/zrythm
    git clone https://git.sr.ht/~alextee/zrythm-builds
    git clone https://git.sr.ht/~alextee/zrythm-installer
    git clone https://github.com/KDE/breeze-icons
    git clone https://github.com/mesonbuild/meson
    echo "$SSH_KEY" > tmp_rsa
    openssl base64 -d -A < tmp_rsa > id_rsa
    grep -q "BEGIN RSA PRIVATE KEY" id_rsa
    chmod 600 id_rsa
    zrythm-builds/scripts/create-manuals-zip.sh osx-brew-zip
    zrythm-builds/scripts/make-pkg.sh osx-brew-zip
    zrythm-builds/scripts/push-pkg.sh osx-brew-zip
  displayName: 'Build OSX'
  env:
    REMOTE_HOME: $(REMOTE_HOME)
    REMOTE_IP: $(REMOTE_IP)
    SSH_KEY: $(SSH_KEY)
